language: android

sudo: required

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-android-m2repository

before_script:
  - wget https://dl.google.com/android/repository/android-ndk-r14-linux-x86_64.zip
  - unzip -q android-ndk-r14-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$(pwd)/android-ndk-r14
  - wget https://github.com/opencv/opencv/releases/download/3.1.0/OpenCV-3.1.0-android-sdk.zip
  - unzip -q OpenCV-3.1.0-android-sdk.zip
  - export OPENCV_ANDROID_SDK=$(pwd)/OpenCV-android-sdk
  - wget https://bitbucket.org/eigen/eigen/get/3.3.0.zip -O Eigen3.zip
  - unzip -q Eigen3.zip
  - export EIGEN3_DIR=$(dirname $(find $(pwd) -type f -name 'signature_of_eigen3_matrix_library' -print -quit))

script:
  ./gradlew build
